linters:
  default: all
  disable:
    - contextcheck
    - cyclop
    - depguard
    - err113
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - lll
    - mnd
    - nestif
    - paralleltest
    - revive
    - tagliatelle
    - testpackage
    - unparam
    - varnamelen
    - wrapcheck
    - maintidx
version: "2"