linters:
  default: all
  disable:
    - exhaustruct
    - varnamelen
    - funlen
    - gocognit
    - cyclop
    - lll
    - mnd
    - revive
    - gochecknoglobals
    - paralleltest
    - contextcheck
    - depguard
    - err113
    - forbidigo
    - gochecknoinits
    - gocyclo
    - nestif
    - staticcheck
    - tagliatelle
    - testpackage
    - unparam
    - wrapcheck
    - wsl
    - maintidx
version: "2"